# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.api_boundaries_url: '%env(MOBILE_DETAIL_BOUNDARIES)%'
    app.api_incidents_url:
        restores: '%env(MOBILE_DETAIL_RESTORES)%'
        incidents: '%env(MOBILE_DETAIL_INCIDENTS)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Command\FetchOutagesCommand:
        arguments:
            $apiBoundariesUrl: '%app.api_boundaries_url%'
            $apiIncidentUrls: '%app.api_incidents_url%'