services:
#    epboutage_main.example:
#        class: EPBOutage\MainBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    epboutage.outage_importer:
        class: EPBOutage\MainBundle\Import\OutageImporter
        arguments: [@doctrine_mongodb.odm.document_manager]
        
    epboutage.old_outage_importer:
        class: EPBOutage\MainBundle\Import\OldOutageImporter
        arguments: [@doctrine_mongodb.odm.document_manager]
        
    epboutage.alert_sender:
        class: EPBOutage\MainBundle\Services\AlertSender
        arguments: [@service_container, @doctrine_mongodb.odm.document_manager, @mailer, @templating]